name: First Workflow

on:
  push: 
    branches: 
      - main

jobs:
  welcome-file:
    runs-on: ubuntu-latest

    steps:
      - name: write welcome message
        run: echo "Hello World from Github actions! Abdulwahab" >> welcome-message.txt
      
      - name: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: welcome artifact
          path: welcome-message.txt


  read-file:
    needs: welcome-file
    runs-on: ubuntu-latest
    steps:
      - name: download-artifact
        uses: actions/download-artifact@v5
        with:
          name: welcome artifact

      - name: read welcome message file
        run: cat welcome-message.txt


      