name: First Workflow

on:
  push: 
    branches: 
      - main

jobs:
  welcome-file:
    runs-on: ubuntu-latest

    steps:
      - name: write welcome message
        run: echo "Hello World from Github actions! Abdulwahab" >> welcome-message.txt
       

  list-files:
    needs: welcome-file
    runs-on: ubuntu-latest

    steps:
      - name: list files in details
        run: ls -ltra

  read-file:
    needs: list-files
    runs-on: ubuntu-latest
    steps:
      - name: read welcome message file
        run: cat welcome-message.txt


      