name: First Workflow

on:
  push: 
  workflow_dispatch: 


jobs:
  welcome-file:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04]
        images: [hello-world, alpine]
    
    runs-on: ${{ matrix.os }}

    steps:
      - name: Print Docker info
        run: docker info
      
      - name: Run Docker ${{ matrix.images }}
        run: docker run ${{ matrix.images }}

      